name: Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            **/cpm_modules
            **/node_modules
          key: cpm-node-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake', '**/yarn.lock') }}

      - name: setup emsdk
        uses: mymindstorm/setup-emsdk@v14

      - name: setup ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.12.1

      - name: install C++/CMake style checkers
        run: pip3 install clang-format==18.1.8 cmake_format==0.6.13 pyyaml

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: pnpm install
        env:
          CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
        run: pnpm install

      - name: test
        run: pnpm test

      - name: check style
        run: pnpm lint
